### ISSUE TITLE
Circular structure error

### ISSUE THREAD

**Issue by egens** [sindresorhus/jshint-json#1]
From here
https://github.com/AtomLinter/linter-jshint/issues/218

This code with circular structure error leads to error.

``` js
function appear() {
    if (op < 1) {
        op += 0.1;
        tipobj.style.opacity = op;
        tipobj.style.filter = 'alpha(opacity=' + op * 100 + ')';
        t = setTimeout('appear()', 5);
    }
}
```

```
Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4 console.log(JSON.stringify({ ^

TypeError: Converting circular structure to JSON at Object.stringify (native) at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20) at Object. (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39) at Socket. (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18) at emitNone (events.js:72:20) at Socket.emit (events.js:166:7) at endReadableNT (_stream_readable.js:893:12) at doNTCallback2 (node.js:441:9) at process._tickCallback (node.js:355:17)

Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
        console.log(JSON.stringify({
                         ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at parameters.exit (/home/egens/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:131:25)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
        console.log(JSON.stringify({
                         ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at parameters.exit (/home/egens/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:131:25)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by sindresorhus** [comment]
Would you be able to narrow down what in the JSHint result that is circular?

**Comment by egens** [comment]
```
> jshint --reporter /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js ~/Downloads/t.js 

/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
        console.log(JSON.stringify({
                         ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.exports.run (/home/egens/lib/node_modules/jshint/src/cli.js:671:35)
    at Object.exports.interpret (/home/egens/lib/node_modules/jshint/src/cli.js:754:18)
    at Object.<anonymous> (/home/egens/lib/node_modules/jshint/bin/jshint:3:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by sindresorhus** [comment]
No, I mean where in the `result`/`data` object it occurs so I can delete it: https://github.com/sindresorhus/jshint-json/blob/c1e5e95540399cbeb460bec3a7b39f4c0b02cb69/json.js#L3

**Comment by rfartaria** [comment]
Has this been addressed yet?
I'm using the following to circumvent the problem:

```
'use strict';
module.exports = {
    reporter: function (result, data) {
        var seen = [];
        console.log(JSON.stringify({
                        result: result,
                        data: data
                    }, function(key, val) {
                        if (val != null && typeof val == "object") {
                            if (seen.indexOf(val) >= 0) {
                                return;
                            }
                            seen.push(val);
                        }
                        return val;
                    }));
    }
};
```
